In [1]:
# how is pytorch tensor different to numpy array and how is pytorch different from numpy since they are similar in many ways 

In [2]:
'''
Firstly tensor and matrix are very different. Matrix is basically a subset of tensor cuz matrix is 2d while tenors in maths can be 
1d ( scaler) , 2d , 3d , ... , nd. 

now for pytorch tensor , it acts like a numpy array but is very different.
firstly we can store it on gpu which we cant do with numpy array 
next they have .grad() property which we can use to calculate their graidents 
they store compuation graph for the operations performed on the tenosr if we want to stop it 
from storing computation graph say when maybe we want to validate our model and we dont want the validation calculatioin 
to hamper the model training computation graph , we can use with torch.no_grad() property. Moreover using 
.backward() method allows us to perform autograd or backpropagation on the tensor by using the computation graph.


pytorch is different from numpy as pytorch lets us build tensors which are similar yet different from numpy arays moreover pytorch lets 
us perform backpropagation and provides both low and high level apis or methods for builidng and training our models.


'''

'\nFirstly tensor and matrix are very different. Matrix is basically a subset of tensor cuz matrix is 2d while tenors in maths can be \n1d ( scaler) , 2d , 3d , ... , nd. \n\nnow for pytorch tensor , it acts like a numpy array but is very different.\nfirstly we can store it on gpu which we cant do with numpy array \nnext they have .grad() property which we can use to calculate their graidents \nthey store compuation graph for the operations performed on the tenosr if we want to stop it \nfrom storing computation graph say when maybe we want to validate our model and we dont want the validation calculatioin \nto hamper the model training computation graph , we can use with torch.no_grad() property. Moreover using \n.backward() method allows us to perform autograd or backpropagation on the tensor by using the computation graph.\n\n\npytorch is different from numpy as pytorch lets us build tensors which are similar yet different from numpy arays moreover pytorch lets \nus perform backprop

In [3]:
#diff between torch.<method> and torch.<method>_ 

In [4]:
# Answer

# basically stuff ending with _ is inplace that means they will change the original tensor while the stuff not ending with the _
# means it will return a new tensor and wont modify the orignal one 




In [7]:
import torch.nn as nn
import torch


In [11]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cuda


In [20]:
random_tensor = torch.tensor([-1 , -2 , 3 ,4 ,5 ])

In [21]:
random_tensor.dtype

torch.int64

In [22]:
yeah = torch.relu(random_tensor)
print(yeah , random_tensor)

tensor([0, 0, 3, 4, 5]) tensor([-1, -2,  3,  4,  5])


In [23]:
antoher = torch.relu_(random_tensor)
antoher

tensor([0, 0, 3, 4, 5])

In [24]:
random_tensor

tensor([0, 0, 3, 4, 5])

In [ ]:
#Q3