In [1]:
# how is pytorch tensor different to numpy array and how is pytorch different from numpy since they are similar in many ways 

In [2]:
'''
Firstly tensor and matrix are very different. Matrix is basically a subset of tensor cuz matrix is 2d while tenors in maths can be 
1d ( scaler) , 2d , 3d , ... , nd. 

now for pytorch tensor , it acts like a numpy array but is very different.
firstly we can store it on gpu which we cant do with numpy array 
next they have .grad() property which we can use to calculate their graidents 
they store compuation graph for the operations performed on the tenosr if we want to stop it 
from storing computation graph say when maybe we want to validate our model and we dont want the validation calculatioin 
to hamper the model training computation graph , we can use with torch.no_grad() property. Moreover using 
.backward() method allows us to perform autograd or backpropagation on the tensor by using the computation graph.


pytorch is different from numpy as pytorch lets us build tensors which are similar yet different from numpy arays moreover pytorch lets 
us perform backpropagation and provides both low and high level apis or methods for builidng and training our models.


'''

'\nFirstly tensor and matrix are very different. Matrix is basically a subset of tensor cuz matrix is 2d while tenors in maths can be \n1d ( scaler) , 2d , 3d , ... , nd. \n\nnow for pytorch tensor , it acts like a numpy array but is very different.\nfirstly we can store it on gpu which we cant do with numpy array \nnext they have .grad() property which we can use to calculate their graidents \nthey store compuation graph for the operations performed on the tenosr if we want to stop it \nfrom storing computation graph say when maybe we want to validate our model and we dont want the validation calculatioin \nto hamper the model training computation graph , we can use with torch.no_grad() property. Moreover using \n.backward() method allows us to perform autograd or backpropagation on the tensor by using the computation graph.\n\n\npytorch is different from numpy as pytorch lets us build tensors which are similar yet different from numpy arays moreover pytorch lets \nus perform backprop

In [3]:
#diff between torch.<method> and torch.<method>_ 

In [4]:
# Answer

# basically stuff ending with _ is inplace that means they will change the original tensor while the stuff not ending with the _
# means it will return a new tensor and wont modify the orignal one 




In [7]:
import torch.nn as nn
import torch


In [11]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cuda


In [20]:
random_tensor = torch.tensor([-1 , -2 , 3 ,4 ,5 ])

In [21]:
random_tensor.dtype

torch.int64

In [22]:
yeah = torch.relu(random_tensor)
print(yeah , random_tensor)

tensor([0, 0, 3, 4, 5]) tensor([-1, -2,  3,  4,  5])


In [23]:
antoher = torch.relu_(random_tensor)
antoher

tensor([0, 0, 3, 4, 5])

In [24]:
random_tensor

tensor([0, 0, 3, 4, 5])

In [25]:
#Q3 two ways to create tensor on gpu 

In [27]:
# first way is uh create tensor then do .to(device) and set device to cuda

# next ig create a tensor then pass device argument and set it to cuda there 

In [ ]:
# q4 three ways to perform tensor computation without using autograd

In [29]:
# with torch.no_grad()

# in tensor write require_grad=False

#.detach()

In [30]:
# #question 5

# i think it will give a runtime error cuz see like we arent changing the original tensor when we apply .cos 
# so the autograd will be cooked ig 

In [31]:
t = torch.tensor(2.0 , requires_grad=True   )

In [32]:
z = t.cos().exp_()
z.backward()

In [33]:
#nvm it worked 

In [34]:
#pytorch training loop 

In [ ]:
# main steps in pytorch training loop : 

# model.train() to begin training initialization 
# do metric.reset() to flush any prev stuff stored
# then iterate over each epoch in total epoch
# then iterate over train x batch and train y batch from dataloader 
# do forward pass which is prediciting the y_pred or y_logits using the model which is initially using random parameters set using torch.manual_seed() 
# then we can find the loss using appropriate criterion provided in the function argument
# then we can do our optimizer.zero_grad to set the gradients of all optimized var to 0 
# then we can run loss.backward to run backpropagation 
# then we can run optimizer.step to tweak our weight parameters 
# then we can do metric.update to update our training metric so we can get idea about our model we can also print it 
# then we can append total loss which we need to initialize as 0 at the start of every batch 
# then we can basically calculate the mean loss and can print it 
# then we can do model.eval() 
# when we want to perform validation it is necessary as it gives us idea that our model is overfitting or not. 
# remember to use with torch.no_grad() when calculation and updating val metric as we dont want to change our original computation graph which we are builidng for our model. 
# finally we can print everything and do this again for next epoch 

In [35]:
# why create optimizer after moving model to gpu 